// Generated by CoffeeScript 1.6.3
(function() {
  var availableTiles, dict, fs, rootPath, scores, sortWord, word, _i, _len;

  fs = require('fs');

  rootPath = '/Users/matt/Documents/Programming/scrabblesolver/';

  dict = fs.readFileSync(rootPath + 'ospd3.txt', 'utf8');

  sortWord = function(word) {
    return word.split('').sort().join('');
  };

  scores = {
    1: ["E", "A", "I", "O", "N", "R", "T", "L", "S", "U"],
    2: ["D", "G"],
    3: ["B", "C", "M", "P"],
    4: ["F", "H", "V", "W", "Y"],
    5: ["K"],
    8: ["J", "X"],
    10: ["Q", "Z"]
  };

  availableTiles = ['A', 'T', 'U', 'A', 'F', 'A', 'J'];

  if (dict.indexOf('cuello') > -1) {
    console.log('true');
  } else {
    console.log('false');
  }

  for (_i = 0, _len = dict.length; _i < _len; _i++) {
    word = dict[_i];
    console.log(word);
  }

}).call(this);
